# Generated by Django 4.2.3 on 2023-08-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courselist', '0004_remove_topic_description_topic_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='note',
            field=models.TextField(default='N/A'),
        ),
    ]
