# Generated by Django 4.2.3 on 2023-08-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courselist', '0005_topic_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
