# Generated by Django 4.2.3 on 2023-08-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courselist', '0006_alter_topic_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselist',
            name='icon',
            field=models.CharField(choices=[('icon1', 'python'), ('icon2', 'javascript'), ('icon3', 'c'), ('icon4', 'css'), ('icon5', 'java'), ('icon6', 'swift'), ('icon7', 'scala'), ('icon8', 'kotlin'), ('icon9', 'php'), ('icon10', 'ruby'), ('icon11', 'rust'), ('icon12', 'html'), ('icon13', 'default')], default='default', max_length=20),
        ),
    ]
